<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Avatar</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <h1>Avatar - poo -</h1>
    </header>
    <main>

        <div>
            <!-- svg généré -->
            <?=$svg;?>
        </div>
                
        <div>
            <form method="POST" action="index.php">
                <label for="size">Taille</label>
                <input type="text" id="size" name="size" value="" placeholder ="">
                <label for="num_color">Nombre de couleurs</label>
                <input type="text" id="num_color" name="num_color" value="" placeholder ="">
                <p> ... et les couleurs fixées ... </p>
                <input type="submit" value="Générer !">
            </form>
        <?php if (($size != null) && ($nbColor != null)): ?>
        <p>
            La taille :  <?php echo $size; ?> , le nombre de couleurs <?php echo $nbColor; ?> 
        </p>
         <?php endif ;?>
        </div>
    </main>
    
</body>
</html> 